### ISSUE TITLE
Allow users to upload any type of video and image files on client.

### ISSUE THREAD

**Issue by adammendoza** [vidcode/VidCode#9]
Currently upload is limited to 10MB, and .mp4 and .webm files only. About 1 to 2 minutes.

**Comment by msmahliss** [comment]
I was excited to hear that Leandra was able to upload her .mov files! I have not yet replicated this on my end and instead see a black thumb where the video would be. I think it might have something to do with setting the headers in the /video route ?

**Comment by adammendoza** [comment]
I was able to upload an .mov to astra.io which I had exported from the Mac file to astra but a video file from the Phone threw an format error.
